# only build develop, master & production branch
branches:
  only:
    - master
    - develop
    - production
language: node_js
node_js: 10.16.0
before_install:
  - nvm install 10.16.0
  # apply production configuration
  - openssl aes-256-cbc -K $encrypted_7e3db19e27fb_key -iv $encrypted_7e3db19e27fb_iv -in production.zip.enc -out production.zip -d
  - unzip -o production.zip
  - npm install -g yarn
  - yarn
jobs:
  include:
    - stage: Validate
      script: yarn validate &&
        yarn coveralls
    - stage: Publish develop
      if: branch = develop
      script: pip install --user awscli &&
        npm install -g serverless &&
        curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash &&
        yarn job production &&
        yarn serverless-prepare &&
        yarn serverless-deploy
