version: "3"

services:
  web:
    environment:
      - NODE_ENV=development
    build: .
    command: npm run debug
    volumes:
      - ./dist:/node_app/dist
    ports:
      - "3001:3001"
      - "5858:5858"
  mongo:
    image: mongo:4.2.0-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
volumes:
  mongo-db-data:
