CREATE TABLE IF NOT EXISTS shops (
  id VARCHAR(100) NOT NULL UNIQUE PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  domain VARCHAR(100) NOT NULL UNIQUE,
  ownerId VARCHAR(100) NOT NULL UNIQUE,
  address VARCHAR(255) NOT NULL,
  longtitude DECIMAL(6,2) NOT NULL,
  latitude DECIMAL(6,2) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  phoneNo VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL,
  logoUrl VARCHAR(2083) NOT NULL,
  isActive BOOLEAN DEFAULT true,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DECIMAL CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);