org: thinhtran3588
app: t-web-starter-kit
service: t-web-starter-kit-api

plugins:
  - serverless-api-compression

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  timeout: 30 # optional, in seconds, default is 6
  environment:
    NODE_ENV: production

custom:
  contentEncoding:
    contentCompression: 0

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: dist/lamda.handler
    memorySize: 256 # optional, in MB, default is 1024
    description: graphql api for web starter kit
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
